#!/usr/bin/env bash
if [[ -z $1 ]]; then
  echo 'Usage: '$0' [box@server]' && exit 255
fi

rsync -aiz --exclude=deploy --exclude=.git --exclude=.gitignore\
  --exclude=.gitkeep $(dirname $0)/* box@$1:/home/box/
