#!/bin/bash
if [[ -z $1 ]]; then
  echo 'Usage: '$0' [box-name]' && exit 255
fi

monit=$(which monit)
if [[ -z "$monit" ]]; then
  echo 'Install monit and run prepare script first' && exit 255
fi

bin=$(which $1)
if [[ -z $bin ]]; then
  echo 'Service not found. Please insall '$1' first.' && exit 255
fi


if [[ -f /home/box/monit/units/$1 ]]; then
  echo 'Deleting existing service...'
  ./service stop $1
  /bin/rm -f /home/box/monit/units/$1
  ./service reload
fi

echo 'Linking monit unit...'
ln -P /home/box/$1/$1.monit /home/box/monit/units/$1

echo 'Reloading monit...'
./service reload
./service start $1

i_file=$(pwd)/used
[[ ! -f $i_file ]] && touch $i_file
echo $1 >> $i_file
