#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo 'This script must be run as root' && exit 255
fi

# Get systemctl bin
sctl=$(which systemctl)
if [[ -z $sctl ]]; then
  echo 'There is no systemd. No systemctl found.' && exit 255
fi

# Check service exists
bin=$(which monit)

if [[ -z $bin ]]; then
  echo 'No monit found. First install monit.' && exit 255
fi

echo 'Linking systemd...'
ln -P /home/box/systemd/monit.service /usr/lib/systemd/system/monit.service

echo 'Reloading systemd...'
$sctl daemon-reload

echo 'Enabling service by default and starting it...'
$sctl enable monit.service
$sctl start monit.service

