#!/bin/bash
if [[ -z $1 ]]; then
  echo 'Usage: '$0' [box-name]' && exit 255
fi

# Get systemctl bin
monit=$(which monit)
if [[ -z "$monit" ]]; then
  echo 'Install monit and run prepare script first' && exit 255
fi

if [[ -f /home/box/monit/units/$1 ]]; then
  echo 'Deleting existing service...'
  ./service stop $1
  /bin/rm -f /home/box/monit/units/$1
fi

echo 'Reloading monit...'
./service reload

i_file=$(pwd)/used
[[ -f $i_file ]] && grep -v ^$1$ $i_file > $i_file.tmp && mv -f $i_file.tmp $i_file
